export const defaultUrl = "http://localhost:8080/api/v1/";

export const TYPES = {
  LOGIN: "LOGIN",
  GET_TOKKEN: "GET_TOKKEN",
  LOGOUT: "LOGOUT",
  SET_LOADING: "SET_LOADING",
  GET_ARTICLES: "GET_ARTICLES",
  GET_ARTICLE_SELECT: "GET_ARTICLE_SELECT",
  ADD_TO_CARRITO: "ADD_TO_CARRITO",
  SIX_PRODUCTS: "SIX_PRODUCTS",
  REMOVE_ONE_FROM_CARRITO: "REMOVE_ONE_FROM_CARRITO",
  // CLEAR_MENU: "CLEAR_MENU",
  // GET_RECIPES_SEARCH: "GET_RECIPES_SEARCH",
  GET_USERS: "GET_USERS",
  GET_USER_ID: "GET_USER_ID",
};
